// Generated by CoffeeScript 1.6.2
var register;

register = function(type) {
  exports[type.name] = type;
  if (type.uri) {
    return exports[type.uri] = type;
  }
};

register(require('./simple'));

register(require('./text'));

register(require('./text-tp2'));

register(require('./json0'));
