// Generated by CoffeeScript 1.6.2
module.exports = {
  name: 'simple',
  create: function() {
    return {
      str: ""
    };
  },
  apply: function(snapshot, op) {
    var str, _ref;

    if (!((0 <= (_ref = op.position) && _ref <= snapshot.str.length))) {
      throw new Error('Invalid position');
    }
    str = snapshot.str;
    str = str.slice(0, op.position) + op.text + str.slice(op.position);
    return {
      str: str
    };
  },
  transform: function(op1, op2, sym) {
    var pos;

    pos = op1.position;
    if (op2.position < pos || (op2.position === pos && sym === 'left')) {
      pos += op2.text.length;
    }
    return {
      position: pos,
      text: op1.text
    };
  }
};
